import Blogs from "@/components/blogs/Blogs";
import React from "react";

  export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};


const BlogsPage = () => {
  return (
    <div>
      <Blogs></Blogs>
    </div>
  );
};

export default BlogsPage;
