import React from "react";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="bg-base-100 min-h-screen text-neutral">
      {/* Header */}
      <section className="bg-base-200 relative overflow-hidden py-20">
        {/* Decorative circle */}
        <div className="absolute -top-16 -left-16 w-64 h-64 bg-secondary opacity-10 rounded-full"></div>

        <div className="max-w-5xl mx-auto px-4 text-center relative z-10">
          <h1 className="text-5xl font-bold text-primary mb-3">
            About Us
          </h1>
          {/* Underline */}
          <div className="mx-auto mb-6 w-24 h-1 bg-primary rounded-full"></div>
          <p className="text-lg text-neutral-content max-w-2xl mx-auto">
            We make discovering and booking reliable services simple, fast, and hassle-free.
            Our goal is to provide a seamless experience for both customers and service providers.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <section className="max-w-6xl mx-auto px-4 py-16 space-y-12">
        {/* Who We Are */}
        <div className="bg-base-100 p-10 rounded-2xl shadow-lg border border-base-300">
          <h2 className="text-2xl font-semibold text-secondary mb-4">Who We Are</h2>
          <p className="text-neutral leading-relaxed">
            Our platform connects people with trusted service providers in a seamless and transparent way.
            Whether you’re looking for professional services or managing your bookings, we focus on
            simplicity, reliability, and user experience.
          </p>
        </div>

        {/* Our Mission */}
        <div className="bg-base-100 p-10 rounded-2xl shadow-lg border border-base-300">
          <h2 className="text-2xl font-semibold text-secondary mb-4">Our Mission</h2>
          <p className="text-neutral leading-relaxed">
            Our mission is to remove friction from service booking by providing a clean interface,
            secure payments, and real-time updates — all in one place.
          </p>
        </div>

        {/* Why Choose Us */}
        <div className="bg-base-100 p-10 rounded-2xl shadow-lg border border-base-300">
          <h2 className="text-2xl font-semibold text-secondary mb-6">Why Choose Us</h2>
          <ul className="grid sm:grid-cols-2 gap-4 text-neutral">
            <li className="flex items-start gap-2">
              <span className="font-bold text-primary">•</span>
              Easy and fast booking experience
            </li>
            <li className="flex items-start gap-2">
              <span className="font-bold text-primary">•</span>
              Trusted and verified service providers
            </li>
            <li className="flex items-start gap-2">
              <span className="font-bold text-primary">•</span>
              Secure and transparent payments
            </li>
            <li className="flex items-start gap-2">
              <span className="font-bold text-primary">•</span>
              Responsive support when you need it
            </li>
          </ul>
        </div>

        {/* Closing */}
        <div className="bg-base-100 p-8 rounded-2xl shadow-lg border border-base-300 text-center">
          <p className="text-neutral">
            We’re constantly improving to deliver a better experience for both
            customers and service providers.
          </p>
        </div>
      </section>
    </div>
  );
};

export default AboutPage;
