import { RegisterForm } from '@/components/auth/RegisterForm';
import React, { Suspense } from 'react';

  export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};


const RegisterPage = () => {
    return (
        <div>
            <Suspense fallback={<div>Loading...</div>}>
                <RegisterForm></RegisterForm>
            </Suspense>
        </div>
    );
};

export default RegisterPage;