
import LoginForm from '@/components/auth/LoginForm';
import React, { Suspense } from 'react';

  export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};


const LoginPage = () => {
    return (
        <div>
            <Suspense fallback={<div>Loading...</div>}>
      <LoginForm />
    </Suspense>
        </div>
    );
};

export default LoginPage;