import { GetBookings } from "@/actions/server/Booking";
import React from "react";
import { MdOutlineInfo } from "react-icons/md";
import DeleteBooking from "@/components/buttons/DeleteBooking";
import Link from "next/link";

  export const metadata = {
  title: "My Bookings",
  description: "Generated by create next app",
};


const MyBookings = async () => {
 
  const bookings = await GetBookings();  
  if (bookings.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
        <div className="max-w-md">
          <h2 className="text-2xl font-semibold mb-4 text-gray-600">No Bookings Found</h2>
          <p className="text-gray-500 mb-6">
            You have not made any bookings yet. Explore our services and book your first appointment!
          </p>
          <Link href="/services" className="btn btn-primary">
            Browse Services
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div>
      <h1 className="font-bold text-4xl pt-2">My Bookings</h1>
      <div className="overflow-x-auto mt-10">
        <table className="table table-zebra">
          {/* head */}
          <thead>
            <tr>
              <th>SL No.</th>
              <th>Service</th>
              <th>Duration</th>
              <th>Location</th>
              <th>Status</th>
              <th>Total Cost</th>
              <th>Transaction Id</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {bookings.map((booking, index) => (
              <tr key={booking._id}>
                <th>{index + 1}</th>
                <td>{booking.serviceName}</td>
                <td>
                  {booking.durationType === "hour"
                    ? `${booking.durationValue} Hours`
                    : `${booking.durationValue} Days`}
                </td>
                <td>{booking.location.division}</td>
                <td>
                  <span
                    className={`badge ${
                      booking.status === "confirmed"
                        ? "badge-success"
                        : booking.status === "pending"
                          ? "badge-warning"
                          : "badge-error"
                    }`}
                  >
                    {booking.status}
                  </span>
                </td>
                <td>৳{booking.totalCost}</td>
                <td>{booking.transactionId}</td>
                <td className="space-x-2 flex items-center">
                  <Link href={`/my-bookings/${booking._id.toString()}`} className="btn btn-primary">
                    <MdOutlineInfo></MdOutlineInfo>
                  </Link>
                 <DeleteBooking bookingId={booking._id.toString()}></DeleteBooking>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default MyBookings;
