import React from "react";

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

const ContactPage = () => {
  return (
    <div className="bg-base-100 min-h-screen text-neutral">
      {/* Header */}
      <section className="bg-base-200 relative overflow-hidden py-20">
        {/* Decorative circle */}
        <div className="absolute -top-16 -right-16 w-64 h-64 bg-secondary opacity-10 rounded-full"></div>

        <div className="max-w-5xl mx-auto px-4 text-center relative z-10">
          <h1 className="text-5xl font-bold text-primary mb-3">
            Contact Us
          </h1>
          {/* Underline */}
          <div className="mx-auto mb-6 w-24 h-1 bg-primary rounded-full"></div>
          {/* Tagline */}
          <p className="text-lg text-neutral-content max-w-2xl mx-auto">
            Have questions about our childcare or elderly care services? We’re here to help.  
            Reach out to us and our support team will respond promptly.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <section className="max-w-6xl mx-auto px-4 py-16 grid grid-cols-1 md:grid-cols-2 gap-12">
        {/* Contact Info */}
        <div className="bg-base-100 p-10 rounded-2xl shadow-lg border border-base-300">
          <h2 className="text-2xl font-semibold text-primary mb-6">Get in Touch</h2>
          <p className="text-neutral leading-relaxed mb-8">
            Whether you need a reliable caregiver or have questions about our platform,
            feel free to contact us using the information below.
          </p>

          <div className="space-y-6 text-neutral">
            <div>
              <h3 className="font-medium text-secondary">Email</h3>
              <p>support@carenest.io</p>
            </div>
            <div>
              <h3 className="font-medium text-secondary">Phone</h3>
              <p>+8801301235002</p>
            </div>
            <div>
              <h3 className="font-medium text-secondary">Office Address</h3>
              <p>Dhaka, Bangladesh</p>
            </div>
            <div>
              <h3 className="font-medium text-secondary">Working Hours</h3>
              <p>Saturday – Thursday: 9:00 AM – 6:00 PM</p>
            </div>
          </div>
        </div>

        {/* Contact Form */}
        <div className="bg-base-100 p-10 rounded-2xl shadow-lg border border-base-300">
          <h2 className="text-2xl font-semibold text-primary mb-6">Send Us a Message</h2>
          <form className="space-y-5">
            <div>
              <label className="block text-sm font-medium mb-1">Full Name</label>
              <input
                type="text"
                placeholder="Your full name"
                className="w-full border border-base-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Email Address</label>
              <input
                type="email"
                placeholder="you@example.com"
                className="w-full border border-base-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Message</label>
              <textarea
                rows="4"
                placeholder="Write your message here..."
                className="w-full border border-base-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
              ></textarea>
            </div>
            <button
              type="submit"
              className="w-full bg-primary text-base-100 py-3 rounded-lg font-medium hover:bg-primary/90 transition"
            >
              Send Message
            </button>
          </form>
        </div>
      </section>
    </div>
  );
};

export default ContactPage;
