import Service from "@/components/home/Services";
import React from "react";

export const metadata = {
  title: "All Services",
  description: "Generated by create next app",
};

const ServicePage = () => {
  return (
    <div className="min-h-screen">
      <h2 className="text-4xl text-center font-bold mb-15">Our Services</h2>

      <div className="mb-15 flex items-center justify-between">
        <label className="input">
          <svg
            className="h-[1em] opacity-50"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
          >
            <g
              strokeLinejoin="round"
              strokeLinecap="round"
              strokeWidth="2.5"
              fill="none"
              stroke="currentColor"
            >
              <circle cx="11" cy="11" r="8"></circle>
              <path d="m21 21-4.3-4.3"></path>
            </g>
          </svg>
          <input type="search" required placeholder="Search Services" />
        </label>
        <div className="dropdown dropdown-center">
          <div tabIndex={0} role="button" className="btn btn-primary btn-outline m-1">
            Filter By:
          </div>
          <ul
            tabIndex="-1"
            className="dropdown-content menu bg-base-100 rounded-box z-1 w-52 p-2 shadow-sm"
          >
            <li>
              <a>Item 1</a>
            </li>
            <li>
              <a>Item 2</a>
            </li>
          </ul>
        </div>
      </div>
      <Service />
    </div>
  );
};

export default ServicePage;
