import { GetBookings } from "@/actions/server/Booking";
import React from "react";
import { MdOutlineInfo } from "react-icons/md";
import DeleteBooking from "@/components/buttons/DeleteBooking";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { redirect } from "next/navigation";

  export const metadata = {
  title: "My Bookings",
  description: "Generated by create next app",
};


const MyBookings = async () => {
  const session = await getServerSession(authOptions);
  if (!session?.user) {
    redirect('/login?callbackUrl=/my-bookings');
  }
 
  const bookings = await GetBookings();  
  if (bookings.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
        <div className="max-w-md">
          <h2 className="text-2xl font-semibold mb-4 text-primary">No Bookings Found</h2>
          <p className="text-gray-500 mb-6">
            You have not made any bookings yet. Explore our services and book your first appointment!
          </p>
          <Link href="/services" className="btn btn-primary">
            Browse Services
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-primary mb-2">My Bookings</h1>
        <p className="text-sm text-gray-600">View and manage your service bookings</p>
      </div>
      
      <div className="bg-white rounded-lg shadow-lg overflow-hidden border border-gray-200">
        <div className="overflow-x-auto">
          <table className="table w-full">
            <thead className="bg-gradient-to-r from-primary to-primary/80 text-white">
              <tr>
                <th className="text-white font-semibold py-4">SL No.</th>
                <th className="text-white font-semibold py-4">Service</th>
                <th className="text-white font-semibold py-4">Duration</th>
                <th className="text-white font-semibold py-4">Location</th>
                <th className="text-white font-semibold py-4">Status</th>
                <th className="text-white font-semibold py-4">Total Cost</th>
                <th className="text-white font-semibold py-4">Transaction Id</th>
                <th className="text-white font-semibold py-4">Actions</th>
              </tr>
            </thead>
            <tbody>
              {bookings.map((booking, index) => (
                <tr 
                  key={booking._id}
                  className="hover:bg-primary/5 transition-colors duration-150 border-b border-gray-100"
                >
                  <th className="font-medium text-gray-700">{index + 1}</th>
                  <td className="text-gray-800 font-medium">{booking.serviceName}</td>
                  <td className="text-gray-600">
                    {booking.durationType === "hour"
                      ? `${booking.durationValue} Hours`
                      : `${booking.durationValue} Days`}
                  </td>
                  <td className="text-gray-600">{booking.location.division}</td>
                  <td>
                    <span
                      className={`badge ${
                        booking.status === "confirmed"
                          ? "badge-success"
                          : booking.status === "pending"
                            ? "badge-warning"
                            : "badge-error"
                      }`}
                    >
                      {booking.status}
                    </span>
                  </td>
                  <td className="text-green-600 font-semibold">৳{booking.totalCost}</td>
                  <td className="text-gray-600 font-mono text-sm">{booking.transactionId}</td>
                  <td className="space-x-2 flex items-center">
                    <Link href={`/my-bookings/${booking._id.toString()}`} className="btn btn-primary btn-sm">
                      <MdOutlineInfo></MdOutlineInfo>
                    </Link>
                   <DeleteBooking bookingId={booking._id.toString()}></DeleteBooking>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default MyBookings;
